### ISSUE TITLE
Rewrites Meta data

### ISSUE THREAD

**Issue by svobik7** [svobik7/next-i18n-rewrites#2]
Custom meta data should be attach to rewrites rule ir rewrite scope or in page scope.

# Expected behavior

```
{
  root: 'welcome',
  pages: [
    { locale: 'en', metaData: { title: 'EN-welcome-title' }, ... }
  ],
  metaData: { css: [ 'css/welcome.css' ] }
}
```

- [x] `rewrites.table.js` is changed to `rewrites.js`
- [x] named export is used for rewrites table
- [x] named export is used for rewrites meta
- [x] rewrite scope meta data are merged to each page scope during build time
- [x] page scope meta data are available during runtime inside proper page
